language: python
python:
- "3.4"
env:
  - secure: "IvFcRpVKlPdEYaytAWtg52aK8cHbBQ5H9dASKyQkKPVzizuaptnFG6YxNaxaxbZ+KtDDu5HbqxaTtONEGNxJSuhTLUibfgE8SozVuUdNmx3wDLnnCV6oDRzdDeMbi1MoEPaM5KWZX74EQCl61mtjdFTHrauhzQeBSRDlkzXdBfc="
