language: python
python:
  - "2.7"

install: 
  - pip install -r pywikibot/requirements.txt
  - echo "('COPTR Bot', '"$COPTR_PW"')" > passwordfile
  - uname -a
  - gem install jekyll
  - git config user.name "$GIT_NAME"
  - git config user.email $GIT_EMAIL


script:
  - python pywikibot/pwb.py -dir:. login -pass:$COPTR_BOT
  - python projections/powrr-projection.py
  - ./deploy.sh


