language: python
python:
  - "2.7"

install: 
  - pip install -r pywikibot/requirements.txt
  - echo "('COPTR Bot', '"$COPTR_PW"')" > passwordfile
  - uname -a
  - sudo apt-get install ruby2.1 rubygems2.1
  - sudo gem install jekyll
  - git config user.name '$GIT_NAME"
  - git config user.email '$GIT_EMAIL"
  - git config credential.helper "store --file=git-credentials"
  - echo "https://$GH_TOKEN:@github.com" > git-credentials

script:
  - ./login.sh
  - python projections/powrr-projection.py
  - ./deploy.sh


