language: python
python:
  - "2.7"

env:
  - secure: "IvFcRpVKlPdEYaytAWtg52aK8cHbBQ5H9dASKyQkKPVzizuaptnFG6YxNaxaxbZ+KtDDu5HbqxaTtONEGNxJSuhTLUibfgE8SozVuUdNmx3wDLnnCV6oDRzdDeMbi1MoEPaM5KWZX74EQCl61mtjdFTHrauhzQeBSRDlkzXdBfc="
  - secure: "T9qwnFPNX6sOJp493OJm7+/bDjBhUCJzxT22ndl0SaDb8GF507IjxKd9Z57kOp8zEz6Z1MoruXlV6fD5WWgUM9LWZj/dymNSeiMYWn6LURU2FD9vo3F8C+OAVSk9blb3RSAbcZpc6O36reIr8eVAUMK6oqdzY7ctnkmcFR9BPTY="

install: 
  - pip install -r pywikibot/requirements.txt
  - echo "('COPTR Bot', '"$COPTR_PW"')" > passwordfile
  - sudo apt-get install ruby1.9 rubygems1.9
  - sudo gem install jekyll
  - git config user.name '$GIT_NAME"
  - git config user.email '$GIT_EMAIL"
  - git config credential.helper "store --file=git-credentials"
  - echo "https://$GH_TOKEN:@github.com" > git-credentials

script:
  - ./login.sh
  - python projections/powrr-projection.py
  - ./deploy.sh


