language: python
python:
  - "2.7"

before_install:
 - openssl aes-256-cbc -K $encrypted_6e6cf0e3465b_key -iv $encrypted_6e6cf0e3465b_iv -in passwordfile.enc -out passwordfile -d 

install: 
  - pip install -r pywikibot/requirements.txt
  - pip install pyyaml
  - pip install BeautifulSoup
  - git config --global user.name "$GIT_NAME"
  - git config --global user.email $GIT_EMAIL
  - python pywikibot/pwb.py login -family:coptr
  - python pywikibot/pwb.py login -family:ff

script:
  - ./update.sh
  - ./deploy.sh


